import type {
  ActionType,
  Character,
  WorldEvent,
  WorldState,
} from "@/lib/simulation/types";

export type RelationshipChange = {
  /**
   * Character whose relationship is being changed.
   *
   * Example:
   * Zara's suspicion of Daniel changes.
   */
  ownerId: string;

  targetId: string;

  trustDelta?: number;

  suspicionDelta?: number;
};

export type ActionConsequence = {
  actorId: string;

  action: ActionType;

  /**
   * Human-readable rendering of what happened.
   *
   * This is presentation only.
   * The structured event is the actual simulation data.
   */
  event: string;

  knowledgeGained: string[];

  emotionalChange?: string;

  priorityChange?: string;

  relationshipChanges: RelationshipChange[];

  /**
   * Structured event generated by the action.
   */
  worldEvent: WorldEvent;
};

function findCharacter(
  world: WorldState,
  characterId: string
): Character | undefined {
  return world.characters.find(
    (character) =>
      character.id === characterId
  );
}

function clamp(
  value: number,
  min = 0,
  max = 100
): number {
  return Math.max(
    min,
    Math.min(max, value)
  );
}

function updateRelationship(
  character: Character,
  targetId: string,
  trustDelta = 0,
  suspicionDelta = 0
): void {
  const relationship =
    character.relationships.find(
      (item) =>
        item.targetId === targetId
    );

  if (!relationship) {
    return;
  }

  relationship.trust = clamp(
    relationship.trust +
      trustDelta
  );

  relationship.suspicion = clamp(
    relationship.suspicion +
      suspicionDelta
  );
}

function addKnowledge(
  character: Character,
  knowledge: string[]
): void {
  for (const item of knowledge) {
    if (
      !character.knowledge.includes(
        item
      )
    ) {
      character.knowledge.push(
        item
      );
    }
  }
}

function createEventId(
  world: WorldState,
  action: ActionType,
  actorId: string
): string {
  return [
    "day",
    world.day,
    action.toLowerCase(),
    actorId,
    world.eventLog.length + 1,
  ].join("-");
}

function createWorldEvent(
  world: WorldState,
  character: Character,
  action: ActionType,
  data: Record<string, unknown>,
  targetId?: string
): WorldEvent {
  return {
    id: createEventId(
      world,
      action,
      character.id
    ),

    type: "ACTION",

    day: world.day,

    actorId: character.id,

    targetId,

    locationId:
      character.location,

    data: {
      action,
      ...data,
    },
  };
}

export function executeAction(
  world: WorldState,
  character: Character,
  action: ActionType
): ActionConsequence {
  const consequence: ActionConsequence = {
    actorId: character.id,

    action,

    event: "",

    knowledgeGained: [],

    relationshipChanges: [],

    worldEvent:
      createWorldEvent(
        world,
        character,
        action,
        {}
      ),
  };

  switch (action) {
    case "WAIT": {
      consequence.event =
        `${character.name} waits and watches the situation without taking direct action.`;

      consequence.worldEvent.data = {
        action: "WAIT",
      };

      break;
    }

    case "OBSERVE": {
      consequence.event =
        `${character.name} carefully observes what is happening around them.`;

      consequence.worldEvent.data = {
        action: "OBSERVE",
      };

      consequence.emotionalChange =
        "Alert and observant";

      break;
    }

    case "MOVE": {
      const currentLocation =
        world.locations.find(
          (location) =>
            location.id ===
            character.location
        );

      if (
        !currentLocation ||
        currentLocation.connectedTo.length ===
          0
      ) {
        consequence.event =
          `${character.name} remains at ${character.location}.`;

        consequence.worldEvent.data = {
          action: "MOVE",
          success: false,
          from:
            character.location,
        };

        break;
      }

      /*
       * Temporary deterministic movement.
       *
       * This is still something we will improve later.
       * The important change here is that the movement itself
       * is now represented structurally.
       */
      const destinationIndex =
        character.recentActions.length %
        currentLocation.connectedTo.length;

      const destinationId =
        currentLocation.connectedTo[
          destinationIndex
        ];

      const destination =
        world.locations.find(
          (location) =>
            location.id ===
            destinationId
        );

      if (!destination) {
        consequence.event =
          `${character.name} remains at ${character.location}.`;

        consequence.worldEvent.data = {
          action: "MOVE",
          success: false,
          from:
            character.location,
        };

        break;
      }

      const previousLocation =
        character.location;

      character.location =
        destination.id;

      consequence.event =
        `${character.name} moves to ${destination.name}.`;

      consequence.worldEvent.data = {
        action: "MOVE",
        success: true,
        from:
          previousLocation,
        to:
          destination.id,
      };

      break;
    }

    case "TALK": {
      const target =
        world.characters.find(
          (other) =>
            other.id !==
              character.id &&
            other.location ===
              character.location
        );

      if (!target) {
        consequence.event =
          `${character.name} wants to talk but nobody relevant is nearby.`;

        consequence.worldEvent.data = {
          action: "TALK",
          success: false,
        };

        break;
      }

      consequence.event =
        `${character.name} talks with ${target.name}.`;

      consequence.worldEvent.targetId =
        target.id;

      consequence.worldEvent.data = {
        action: "TALK",
        success: true,
        targetId: target.id,
      };

      /*
       * The interaction itself is now generic.
       *
       * Character-specific interpretation will eventually
       * belong to the mind/decision layer rather than being
       * hardcoded here.
       */
      break;
    }

    case "FOLLOW": {
      const target =
        world.characters.find(
          (other) =>
            other.id !==
              character.id &&
            other.location ===
              character.location
        );

      if (!target) {
        consequence.event =
          `${character.name} looks for someone to follow but finds nobody nearby.`;

        consequence.worldEvent.data = {
          action: "FOLLOW",
          success: false,
        };

        break;
      }

      consequence.event =
        `${character.name} quietly follows ${target.name}.`;

      consequence.worldEvent.targetId =
        target.id;

      consequence.worldEvent.data = {
        action: "FOLLOW",
        success: true,
        targetId: target.id,
      };

      /*
       * IMPORTANT:
       *
       * We no longer increase the FOLLOWER'S suspicion here.
       *
       * Following creates an event.
       * The target may later perceive that event and react.
       *
       * This is the beginning of the actor/observer separation
       * we need for believable simulation.
       */
      break;
    }

    case "INVESTIGATE": {
      if (
        !character.capabilities.includes(
          "investigation"
        )
      ) {
        consequence.event =
          `${character.name} attempts to investigate but lacks the necessary capability.`;

        consequence.worldEvent.data = {
          action: "INVESTIGATE",
          success: false,
          reason:
            "missing_capability",
        };

        break;
      }

      const evidence =
        "The company is deliberately approaching students privately.";

      consequence.knowledgeGained.push(
        evidence
      );

      const isNewEvidence =
        !world.evidence.includes(
          evidence
        );

      if (isNewEvidence) {
        world.evidence.push(
          evidence
        );

        consequence.event =
          `${character.name} investigates the company's activities and discovers useful evidence.`;
      } else {
        consequence.event =
          `${character.name} investigates further but finds no new evidence.`;
      }

      consequence.worldEvent.data = {
        action: "INVESTIGATE",
        success: true,
        evidenceFound:
          isNewEvidence,
        evidence,
      };

      break;
    }

    case "SEARCH": {
      const knowledge =
        "Something about the current location suggests the company has been using the area to meet students.";

      consequence.knowledgeGained.push(
        knowledge
      );

      consequence.event =
        `${character.name} searches the area for useful information.`;

      consequence.worldEvent.data = {
        action: "SEARCH",
        success: true,
        knowledgeFound:
          knowledge,
      };

      break;
    }

    default: {
      consequence.event =
        `${character.name} takes no meaningful action.`;

      consequence.worldEvent.data = {
        action,
        success: false,
      };

      break;
    }
  }

  return consequence;
}

export function applyConsequence(
  world: WorldState,
  consequence: ActionConsequence
): void {
  const character =
    findCharacter(
      world,
      consequence.actorId
    );

  if (!character) {
    return;
  }

  /*
   * Apply knowledge to the actor.
   */
  addKnowledge(
    character,
    consequence.knowledgeGained
  );

  /*
   * Apply emotional state.
   */
  if (
    consequence.emotionalChange
  ) {
    character.emotionalState =
      consequence.emotionalChange;
  }

  /*
   * Apply priority.
   */
  if (
    consequence.priorityChange
  ) {
    character.currentPriority =
      consequence.priorityChange;
  }

  /*
   * Apply relationship changes to
   * the explicitly declared owner.
   *
   * This fixes the old model where every relationship change
   * was automatically applied to the actor.
   */
  for (
    const relationshipChange
      of consequence.relationshipChanges
  ) {
    const owner =
      findCharacter(
        world,
        relationshipChange.ownerId
      );

    if (!owner) {
      continue;
    }

    updateRelationship(
      owner,
      relationshipChange.targetId,
      relationshipChange.trustDelta ??
        0,
      relationshipChange.suspicionDelta ??
        0
    );
  }

  /*
   * Append the structured event to the
   * canonical simulation history.
   */
  world.eventLog.push(
    consequence.worldEvent
  );
}
